[2023-12-18 00:49:37,135][flwr][WARNING] - 
Setting `min_available_clients` lower than `min_fit_clients` or
`min_evaluate_clients` can cause the server to fail when there are too few clients
connected to the server. `min_available_clients` must be set to a value larger
than or equal to the values of `min_fit_clients` and `min_evaluate_clients`.

[2023-12-18 00:49:37,138][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2023-12-18 00:49:40,427][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'node:172.16.20.30': 1.0, 'object_store_memory': 59843470540.0, 'memory': 129634764596.0, 'CPU': 64.0}
[2023-12-18 00:49:40,428][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
[2023-12-18 00:49:40,428][flwr][INFO] - No `client_resources` specified. Using minimal resources for clients.
[2023-12-18 00:49:40,428][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
[2023-12-18 00:49:40,458][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 64 actors
[2023-12-18 00:49:40,458][flwr][INFO] - Initializing global parameters
[2023-12-18 00:49:40,458][flwr][INFO] - Requesting initial parameters from one random client
[2023-12-18 00:49:44,675][flwr][INFO] - Received initial parameters from one random client
[2023-12-18 00:49:44,675][flwr][INFO] - Evaluating initial parameters
[2023-12-18 00:49:47,475][flwr][INFO] - initial parameters (loss, other metrics): 0.11523293323516846, {'accuracy': 0.0917}
[2023-12-18 00:49:47,476][flwr][INFO] - FL starting
[2023-12-18 00:49:47,476][flwr][DEBUG] - fit_round 1: strategy sampled 10 clients (out of 100)
[2023-12-18 00:49:58,055][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 7 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:58,055][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 7 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,231][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 86 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,232][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 34 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,233][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 86 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,233][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 34 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,233][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19673, ip=172.16.20.30, actor_id=22a7db906788f275e66f364e01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff9e4b89550>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19673, ip=172.16.20.30, actor_id=22a7db906788f275e66f364e01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff9e4b89550>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 91 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,234][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19673, ip=172.16.20.30, actor_id=22a7db906788f275e66f364e01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff9e4b89550>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19673, ip=172.16.20.30, actor_id=22a7db906788f275e66f364e01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff9e4b89550>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 91 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,236][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 54 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,236][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 94 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,237][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 35 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,237][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19675, ip=172.16.20.30, actor_id=c0ada300484aced6b33a634b01000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f83cc2adc50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 54 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,237][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 94 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,238][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19672, ip=172.16.20.30, actor_id=7eecf98037c76971183f041401000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7fafec335a50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 35 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,238][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19671, ip=172.16.20.30, actor_id=f4439578ea68d72851ed515501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f12bcb2e810>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19671, ip=172.16.20.30, actor_id=f4439578ea68d72851ed515501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f12bcb2e810>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 57 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,238][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 50 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:49:59,239][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19671, ip=172.16.20.30, actor_id=f4439578ea68d72851ed515501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f12bcb2e810>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19671, ip=172.16.20.30, actor_id=f4439578ea68d72851ed515501000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f12bcb2e810>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 57 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:49:59,239][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19676, ip=172.16.20.30, actor_id=203a04a467bc5e2d3e8d395301000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f66b40a6b10>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 50 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:50:01,089][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 76 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:50:01,090][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 76 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, self.valloader, local_epochs, optim, self.device, verbose=False)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:50:01,090][flwr][DEBUG] - fit_round 1 received 0 results and 10 failures
[2023-12-18 00:50:03,793][flwr][INFO] - fit progress: (1, 0.11523293361663818, {'accuracy': 0.0917}, 16.31671432899998)
[2023-12-18 00:50:03,794][flwr][DEBUG] - evaluate_round 1: strategy sampled 100 clients (out of 100)
[2023-12-18 00:51:58,016][flwr][DEBUG] - evaluate_round 1 received 100 results and 0 failures
[2023-12-18 00:51:58,021][flwr][WARNING] - No evaluate_metrics_aggregation_fn provided
[2023-12-18 00:51:58,022][flwr][DEBUG] - fit_round 2: strategy sampled 10 clients (out of 100)
[2023-12-18 00:52:06,992][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 52 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:52:06,992][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 52 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:52:07,033][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 31 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:52:07,033][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 80 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:52:07,034][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 31 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:52:07,034][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 80 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:52:09,331][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 92 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:52:09,332][flwr][ERROR] - Traceback (most recent call last):
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
                   ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 57 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)

[2023-12-18 00:52:09,332][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19666, ip=172.16.20.30, actor_id=437beffcb33196b5f61e2f8001000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f48dc25e750>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 92 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
[2023-12-18 00:52:09,332][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
                  ^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit
    result = train(self.model, self.trainloader, local_epochs, optim, self.device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: train() missing 1 required positional argument: 'device'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=19668, ip=172.16.20.30, actor_id=d538b20bfbffc55df9a2f07601000000, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7f62b0159c50>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 57 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n                  ^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 191, in fit\n    return maybe_call_fit(\n           ^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/client.py", line 223, in maybe_call_fit\n    return client.fit(fit_ins)\n           ^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/.conda/envs/flower-simulation/lib/python3.11/site-packages/flwr/client/numpy_client.py", line 227, in _fit\n    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/tunguyen/federated-learning/project3/client.py", line 34, in fit\n    result = train(self.model, self.trainloader, local_epochs, optim, self.device)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: train() missing 1 required positional argument: \'device\'\n',)
